### ISSUE TITLE
Mac throwing exception after brew install

### ISSUE THREAD

**Issue by neil-joule** [lightbend/reactive-cli#166]
I just tried to install the reactive-cli with brew on a new machine and I’m getting an expception when running rp version or rp. Any suggestions?

```
➜ ~ brew install lightbend/tools/reactive-cli
==> Installing reactive-cli from lightbend/tools
==> Downloading https://bintray.com/lightbend/generic/download_file?file_path=reactive-cli-1.3.0-Mac_OS_X-x86_64.zip
Already downloaded: /Users/User/Library/Caches/Homebrew/reactive-cli-1.3.0.zip
:beer: /usr/local/Cellar/reactive-cli/1.3.0: 4 files, 15.3MB, built in 1 second
➜ ~ rp version
java.io.IOException
at java.lang.Throwable.fillInStackTrace(Unknown Source)
at java.lang.Throwable.init(Unknown Source)
at java.lang.Exception.init(Unknown Source)
at java.io.IOException.init(Unknown Source)
at java.io.IOException.init(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView.scala$scalanative$nio$fs$NativePosixFileAttributeView$$getGroup(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2.scala$scalanative$nio$fs$NativePosixFileAttributeView$$anon$$fileGroup(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anon$1$$anonfun$1.apply(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anon$1$$anonfun$1.apply(Unknown Source)
at scala.scalanative.native.Zone$.apply(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2$$anon$1.init(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView$$anon$2.group(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView.asMap(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView.asMap(Unknown Source)
at java.nio.file.attribute.FileAttributeView$class$.getAttribute(Unknown Source)
at scala.scalanative.nio.fs.NativePosixFileAttributeView.getAttribute(Unknown Source)
at java.nio.file.Files$.getAttribute(Unknown Source)
at java.nio.file.Files$.size(Unknown Source)
at java.nio.file.Files$.readAllBytes(Unknown Source)
at com.lightbend.rp.reactivecli.Platform$.readFile(Unknown Source)
at com.lightbend.rp.reactivecli.files.package$.readFile(Unknown Source)
at com.lightbend.rp.reactivecli.process.NativeProcess$$anonfun$exec$1$$anonfun$apply$1.apply(Unknown Source)
at com.lightbend.rp.reactivecli.process.NativeProcess$$anonfun$exec$1$$anonfun$apply$1.apply(Unknown Source)
at scala.scalanative.native.Zone$.apply(Unknown Source)
at com.lightbend.rp.reactivecli.process.NativeProcess$$anonfun$exec$1.apply(Unknown Source)
at com.lightbend.rp.reactivecli.process.NativeProcess$$anonfun$exec$1.apply(Unknown Source)
at com.lightbend.rp.reactivecli.Platform$.withTempFile(Unknown Source)
at com.lightbend.rp.reactivecli.files.package$.withTempFile(Unknown Source)
at com.lightbend.rp.reactivecli.process.NativeProcess$.exec(Unknown Source)
at com.lightbend.rp.reactivecli.Platform$.processExec(Unknown Source)
at com.lightbend.rp.reactivecli.process.package$.exec(Unknown Source)
at com.lightbend.rp.reactivecli.process.kubectl$.apiVersions$lzycompute(Unknown Source)
at com.lightbend.rp.reactivecli.process.kubectl$.findApi(Unknown Source)
at com.lightbend.rp.reactivecli.argparse.kubernetes.KubernetesArgs$.DefaultIngressApiVersion$lzycompute(Unknown Source)
at com.lightbend.rp.reactivecli.argparse.kubernetes.KubernetesArgs$.DefaultIngressApiVersion(Unknown Source)
at com.lightbend.rp.reactivecli.argparse.InputArgs$$anon$1.init(Unknown Source)
at com.lightbend.rp.reactivecli.argparse.InputArgs$.parser(Unknown Source)
at com.lightbend.rp.reactivecli.Main$.init(Unknown Source)
at com.lightbend.rp.reactivecli.Main$.load(Unknown Source)
at .main(Unknown Source)
➜ ~
```

**Comment by neil-joule** [comment]
I think it was a file permission issue.  Running it as sudo once has seemingly fixed the problem.
